version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - /.env

  web:
    volumes:
      - .:/app
    build:
      context: .
    restart: always
    command: bash -c "alembic upgrade head && uvicorn questions_task.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - /.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dbdata:
